/**
 * The remaining write surfaces, driven through the UI against the real backend:
 * bulk import, tender edit + delete, project edit + delete, and the matches card.
 *
 * The import fixture is a real .xlsx, because the endpoint parses uploads with openpyxl
 * — a CSV is rejected. Generated by scripts/make-import-fixture.py.
 *
 *   node scripts/e2e-crud.mjs --fixture=<path to .xlsx> --number=<tender number>
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { chromium } from "@playwright/test";

const APP = "http://localhost:3000";
const ANALYST = { email: "analyst@example.com", password: "password123" };

let failures = 0;
const check = (name, ok, extra = "") => {
  if (!ok) failures += 1;
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${extra ? `  — ${extra}` : ""}`);
};

const arg = (n, d) => process.argv.find((a) => a.startsWith(`--${n}=`))?.slice(n.length + 3) ?? d;
const fixture = arg("fixture", path.join(os.tmpdir(), "import-fixture.xlsx"));
const stamp = arg("number", String(Date.now() % 10000));

if (!fs.existsSync(fixture)) {
  console.error(`fixture not found: ${fixture}`);
  console.error("generate it first:  python scripts/make-import-fixture.py <out.xlsx> <suffix>");
  process.exit(2);
}

const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const pageErrors = [];
page.on("pageerror", (e) => pageErrors.push(e.message));

await page.goto(`${APP}/login`, { waitUntil: "load" });
await page.getByLabel("Email").fill(ANALYST.email);
await page.getByLabel("Password").fill(ANALYST.password);
await page.getByRole("button", { name: "Sign in" }).click();
await page.waitForURL("**/dashboard", { timeout: 15000 }).catch(() => {});

// --- CSV import -------------------------------------------------------------
await page.goto(`${APP}/tenders`, { waitUntil: "load" });
await page.waitForTimeout(1200);
await page.getByRole("button", { name: /Import spreadsheet/ }).click();
await page.waitForTimeout(500);
await page.setInputFiles('input[accept^=".xlsx"]', fixture);
await page.waitForTimeout(3500);

let body = await page.evaluate(() => document.body.innerText);
check("import reports created rows", /\b1 created\b/.test(body), body.match(/\d+ created/)?.[0]);
check("import reports the duplicate as skipped, not fatal", /\b1 skipped\b/.test(body));
check("per-row outcomes are listed", body.includes("CREATED") && body.includes("SKIPPED"));

// --- tender edit ------------------------------------------------------------
await page.goto(`${APP}/tenders`, { waitUntil: "load" });
await page.waitForTimeout(1200);
await page.getByLabel("Search").fill("Imported drainage");
await page.waitForTimeout(1500);
await page.locator("tbody tr a").first().click();
await page.waitForTimeout(1600);
const importedUrl = page.url();

await page.getByRole("button", { name: "Edit" }).first().click();
await page.waitForTimeout(600);
await page.getByLabel("Department").fill("Public Works (Zone 2)");
await page.getByRole("button", { name: /Save changes/ }).click();
await page.waitForTimeout(2200);
body = await page.evaluate(() => document.body.innerText);
check("tender edit persists", body.includes("Public Works (Zone 2)"));

// --- matches card -----------------------------------------------------------
check(
  "matching past projects rendered",
  body.includes("Matching past projects"),
);

// --- project create, edit, delete -------------------------------------------
await page.goto(`${APP}/projects`, { waitUntil: "load" });
await page.waitForTimeout(1400);
await page.getByRole("button", { name: /Add project/ }).click();
await page.waitForTimeout(500);
await page.getByLabel("Name").fill(`Temp project ${stamp}`);
await page.getByLabel("Work value").fill("1234567.00");
await page.getByRole("button", { name: /Save project/ }).click();
await page.waitForTimeout(2200);
body = await page.evaluate(() => document.body.innerText);
check("project created", body.includes(`Temp project ${stamp}`));
check("project money formatted", body.includes("12,34,567"));

const row = page.locator("tbody tr", { hasText: `Temp project ${stamp}` });
await row.getByRole("button", { name: "Edit" }).click();
await page.waitForTimeout(700);
await page.getByLabel("Client").fill("Municipal Corporation");
await page.getByRole("button", { name: /Save changes/ }).click();
await page.waitForTimeout(2200);
body = await page.evaluate(() => document.body.innerText);
check("project edit persists", body.includes("Municipal Corporation"));

const row2 = page.locator("tbody tr", { hasText: `Temp project ${stamp}` });
await row2.getByRole("button", { name: "Delete" }).click();
await page.waitForTimeout(400);
check("delete asks for confirmation first", (await page.getByRole("button", { name: /Delete permanently/ }).count()) > 0);
await page.getByRole("button", { name: /Delete permanently/ }).click();
await page.waitForTimeout(2200);
body = await page.evaluate(() => document.body.innerText);
check("project deleted", !body.includes(`Temp project ${stamp}`));

// --- tender delete ----------------------------------------------------------
await page.goto(importedUrl, { waitUntil: "load" });
await page.waitForTimeout(1600);
await page.getByRole("button", { name: "Delete" }).first().click();
await page.waitForTimeout(400);
await page.getByRole("button", { name: /Delete permanently/ }).click();
await page.waitForTimeout(2500);
check("tender delete returns to the list", new URL(page.url()).pathname === "/tenders", new URL(page.url()).pathname);

await page.waitForTimeout(1200);
body = await page.evaluate(() => document.body.innerText);
check("deleted tender is gone from the list", !body.includes("Imported drainage"));

await browser.close();


if (pageErrors.length) {
  console.log(`\n${pageErrors.length} page error(s):`);
  for (const e of [...new Set(pageErrors)].slice(0, 4)) console.log(`  ${e}`);
  failures += 1;
} else {
  console.log("\nNo page errors.");
}
console.log(failures ? `\n${failures} check(s) failed.` : "\nAll write surfaces work end to end.");
process.exit(failures ? 1 : 0);
